plugins {
    id "com.android.application"
    id "com.chaquo.python"
}

android {
    namespace = "com.ytet.android"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.ytet.android"
        minSdk = 26
        targetSdk = 36
        versionCode = 3
        versionName = "0.1.2-android"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

}

dependencies {
    implementation "com.mrljdx:ffmpeg-kit-full:6.1.4"
    testImplementation "junit:junit:4.13.2"
}

chaquopy {
    defaultConfig {
        version = "3.12"
        buildPython "python3.12"
        pip {
            install("yt-dlp==2026.3.17")
            install("yt-dlp-ejs==0.8.0")
            install("mutagen==1.47.0")
        }
    }
}
